version: '3.9'
services:
  elastic-search:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.6.2'
    container_name: elastic-search-dcc
    hostname: elastic-search-dcc
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
    ports:
      - '9200:9200'
    networks:
      - dcc-network
  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.6.2'
    container_name: kibana-dcc
    hostname: kibana-dcc
    ports:
      - '5601:5601'
    networks:
      - dcc-network
  logstash:
    image: 'docker.elastic.co/logstash/logstash:8.6.2'
    container_name: logstash-dcc
    hostname: logstash-dcc
    ports:
      - '5044:5044'
    networks:
      - dcc-network
    volumes:
      - './logstash/pipeline/:/usr/share/logstash/pipeline/'
      - './logstash/config/:/usr/share/logstash/config/'
networks:
  dcc-network: null
